### PR TITLE
Add twrl executable

### PR DESCRIPTION
**Pull request by mugman174**
For easy use and stuff

### CODE REVIEW

**Comment by mugman174** [comment]
hehehe

**Comment by mugman174** [comment]
can someone @here merge this pls (`code` ||spoiler||)

**Review by thewarsawpakt — CHANGES_REQUESTED** [review]
Change the exit code, please.

**Review by thewarsawpakt — APPROVED** [review]

**Review by thewarsawpakt — APPROVED** [review]

**Comment by mugman174** [comment]
theres more updoots

**Pull request merged**
