### PR TITLE
Fix existing dep resolution

### PR DESCRIPTION
**Pull request by Sophon96**
Adds a search function which uses `localdb.search()` and checks every package returned's provides. Also fixes the way that .so's are searched for.

### CODE REVIEW

**Comment by Sophon96** [comment]
@thewarsawpakt Review and merge?

**Comment by caughtquick** [comment]
This looks good, someone give another approval and merge

**Comment by Sophon96** [comment]
Hey why am I not part of the org

**Comment by Sophon96** [comment]
And why don't I have write access

**Comment by thewarsawpakt** [comment]
@

> @thewarsawpakt Review and merge?
Already reviewed, once I figure out how to merge it correctly I will.

**Comment by Sophon96** [comment]
bruh

**Comment by Sophon96** [comment]
Push the big grean button

**Comment by Sophon96** [comment]
yayayayayayay

**Pull request merged**
